import { Users, Mountain, Bike, Palette, Utensils, Music, Dumbbell } from "lucide-react";

// Activity-based communities shown during circle onboarding – great for
// social / dating contexts, but no explicit dating mention.
export const availableCircles = [
  {
    id: 1,
    name: "Hiking Explorers",
    description: "Weekly group hikes on scenic trails – all levels welcome",
    members: 342,
    image: "https://images.unsplash.com/photo-1551632811-561732d1e306?w=200&h=200&fit=crop",
    category: "Outdoor Activities",
    icon: Mountain,
    bgColor: "bg-emerald-50",
    iconBg: "bg-emerald-100",
    iconColor: "text-emerald-600",
  },
  {
    id: 2,
    name: "Morning Run Club",
    description: "Casual runs followed by coffee & chat",
    members: 278,
    image: "https://images.unsplash.com/photo-1551698618-1dfe5d97d256?w=200&h=200&fit=crop",
    category: "Fitness",
    icon: Dumbbell,
    bgColor: "bg-rose-50",
    iconBg: "bg-rose-100",
    iconColor: "text-rose-600",
  },
  {
    id: 3,
    name: "Weekend Warriors",
    description: "Outdoor adventures: camping, kayaking, rock climbing",
    members: 198,
    image: "https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?w=200&h=200&fit=crop",
    category: "Outdoor Activities",
    icon: Bike,
    bgColor: "bg-blue-50",
    iconBg: "bg-blue-100",
    iconColor: "text-blue-600",
  },
  {
    id: 4,
    name: "Cooking Together",
    description: "Group cooking classes and potluck dinners",
    members: 310,
    image: "https://images.unsplash.com/photo-1556911220-e15b29be8c8f?w=200&h=200&fit=crop",
    category: "Food & Social",
    icon: Utensils,
    bgColor: "bg-orange-50",
    iconBg: "bg-orange-100",
    iconColor: "text-orange-600",
  },
  {
    id: 5,
    name: "Sunset Beach Volleyball",
    description: "Casual games on the sand, then sunset watching",
    members: 264,
    image: "https://images.unsplash.com/photo-1612872087720-bb876e6e67d1?w=200&h=200&fit=crop",
    category: "Sports & Social",
    icon: Users,
    bgColor: "bg-yellow-50",
    iconBg: "bg-yellow-100",
    iconColor: "text-yellow-600",
  },
  {
    id: 6,
    name: "Dance & Move",
    description: "Salsa, swing, and partner dance nights for fun",
    members: 189,
    image: "https://images.unsplash.com/photo-1508700115892-45ecd05ae2ad?w=200&h=200&fit=crop",
    category: "Arts & Social",
    icon: Music,
    bgColor: "bg-purple-50",
    iconBg: "bg-purple-100",
    iconColor: "text-purple-600",
  },
  {
    id: 7,
    name: "Wine & Paint Nights",
    description: "Relaxed evenings of painting, sipping, and chatting",
    members: 156,
    image: "https://images.unsplash.com/photo-1513364776144-60967b0f800f?w=200&h=200&fit=crop",
    category: "Arts & Social",
    icon: Palette,
    bgColor: "bg-pink-50",
    iconBg: "bg-pink-100",
    iconColor: "text-pink-600",
  },
];

export const onboardingCategories = [
  "All",
  "Outdoor Activities",
  "Fitness",
  "Food & Social",
  "Sports & Social",
  "Arts & Social",
];
