import { useState } from "react";
import { Send } from "lucide-react";
import { useNavigate } from "react-router-dom";
import { useTranslation } from "react-i18next";
import { useComments, useCreateComment, useReplyToComment, useDeleteComment } from "../../hooks/useComments";
import { useMyProfile } from "../../../UserProfile/Hooks/useMyProfile";
import { useReportUser } from "../../../UserHome/api";
import ReportUserModal from "../../../UserHome/components/Modals/ReportUserModal";
import CommentCard from "./CommentCard";
import BottomSheetModal from "../common/BottomSheetModal";
import { DEFAULT_AVATAR, formatPostTime as formatCommentTime } from "../../utils/postDisplay";
import { CommentSkeleton } from "../common/Skeletons";

const COMMENT_MAX_LENGTH = 500;

export default function CommentSection({ isOpen, onClose, post }) {
  const { t } = useTranslation("circles");
  const navigate = useNavigate();
  const [newComment, setNewComment] = useState("");
  const [replyingTo, setReplyingTo] = useState(null);
  const [replyText, setReplyText] = useState("");
  const [reportComment, setReportComment] = useState(null);

  const postId = post?.postId;
  const {
    comments,
    isLoading,
    fetchNextPage: fetchNextComments,
    hasNextPage: hasMoreComments,
    isFetchingNextPage: isFetchingMoreComments,
  } = useComments(postId);
  const createCommentMutation = useCreateComment(postId);
  const replyCommentMutation = useReplyToComment(postId);
  const deleteCommentMutation = useDeleteComment(postId);
  const { mutate: reportUser } = useReportUser();

  const { data: myProfile } = useMyProfile();

  // Strip "USER#" prefix from PK to compare against bare authorId from post
  const myId = myProfile?.username?.replace(/^USER#/, "") ?? "";
  const isPostAuthor = !!myId && myId === post?.authorId;

  if (!isOpen) return null;

  const handleSubmitComment = (e) => {
    e.preventDefault();
    const content = newComment.trim();
    if (!content || content.length > COMMENT_MAX_LENGTH || !postId || createCommentMutation.isPending) return;

    createCommentMutation.mutate(
      {
        content,
        circleId: post.circleId,
        createdAtEpoch: String(post.createdAtEpoch),
        authorImage: myProfile?.profilePhoto || "",
        authorName: myProfile?.name || "",
        authorId: myId,
        // Generated once per submit attempt (not regenerated by
        // axios-retry, which resends this exact request body) — lets the
        // backend recognize a retried create as the same comment instead of
        // creating a duplicate, and doubles as the optimistic entry's key.
        clientCommentId: crypto.randomUUID(),
      },
      {
        onSuccess: () => setNewComment(""),
      }
    );
  };

  const handleSubmitReply = (e, comment) => {
    e.preventDefault();
    const content = replyText.trim();
    if (!content || content.length > COMMENT_MAX_LENGTH || !postId || replyCommentMutation.isPending) return;

    replyCommentMutation.mutate(
      {
        content,
        circleId: post.circleId,
        createdAtEpoch: String(post.createdAtEpoch),
        parentCommentId: comment.commentId || comment.id,
        authorImage: myProfile?.profilePhoto || "",
        authorName: myProfile?.name || "",
        authorId: myId,
        clientCommentId: crypto.randomUUID(),
      },
      {
        onSuccess: () => {
          setReplyText("");
          setReplyingTo(null);
        },
      }
    );
  };

  return (
    <>
    <BottomSheetModal
      isOpen={isOpen}
      onClose={onClose}
      panelClassName="max-w-lg h-[80vh] sm:h-[70vh] sm:rounded-2xl flex flex-col"
    >
        {/* Header */}
        <div className="flex-shrink-0 p-4 border-b border-gray-100 flex items-center justify-between">
          <div>
            <h3 className="text-lg font-bold text-gray-800">{t("comments.header")}</h3>
            {post?.title && (
              <p className="text-xs text-gray-500 mt-0.5">{post.title}</p>
            )}
          </div>
          <button
            onClick={onClose}
            className="p-2 hover:bg-gray-100 rounded-full transition-colors"
          >
            <svg className="w-5 h-5 text-gray-500" fill="none" viewBox="0 0 24 24" stroke="currentColor">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M6 18L18 6M6 6l12 12" />
            </svg>
          </button>
        </div>

        {/* Comments List */}
        <div
          role="log"
          aria-live="polite"
          aria-relevant="additions"
          className="flex-1 overflow-y-auto p-4 space-y-4"
        >
          {isLoading && (
            <>
              <CommentSkeleton />
              <CommentSkeleton />
              <CommentSkeleton />
            </>
          )}

          {!isLoading && comments.length === 0 && (
            <p className="text-sm text-gray-400 text-center py-4">{t("comments.empty")}</p>
          )}

          {comments.map((comment) => {
            const commentAuthor = comment.authorName || comment.author?.name || comment.userName || comment.name;
            const commentKey = comment.commentId || comment.id;
            const isReplying = replyingTo === commentKey;

            return (
              <CommentCard
                key={commentKey}
                avatar={comment.authorImage || comment.author?.avatar || comment.avatar || DEFAULT_AVATAR}
                name={commentAuthor || t("common.anonymous")}
                text={comment.content || comment.text || comment.body}
                time={comment.isPending ? t("comments.posting") : formatCommentTime(comment.createdAtEpoch)}
                likes={comment.likes ?? 0}
                isPending={comment.isPending}
                onAuthorClick={
                  comment.authorId
                    ? () => navigate(`/profile/${comment.authorId}`)
                    : undefined
                }
                onDelete={
                  !comment.isPending && (isPostAuthor || (myId && myId === comment.authorId))
                    ? () => deleteCommentMutation.mutate(commentKey)
                    : undefined
                }
                onReport={
                  !comment.isPending && comment.authorId && myId !== comment.authorId
                    ? () => setReportComment({ commentId: commentKey, authorId: comment.authorId })
                    : undefined
                }
                onReply={!comment.isPending && isPostAuthor ? () => setReplyingTo(isReplying ? null : commentKey) : undefined}
                replies={(comment.replies || []).map((reply) => ({
                  commentId: reply.commentId || reply.id,
                  avatar: reply.authorImage || reply.author?.avatar || reply.avatar || DEFAULT_AVATAR,
                  name: reply.authorName || reply.author?.name || reply.userName || reply.name || t("common.anonymous"),
                  text: reply.content || reply.text || reply.body,
                  time: reply.isPending ? t("comments.posting") : formatCommentTime(reply.createdAtEpoch),
                  likes: reply.likes ?? 0,
                  isPending: reply.isPending,
                  onAuthorClick: reply.authorId
                    ? () => navigate(`/profile/${reply.authorId}`)
                    : undefined,
                  onDelete:
                    !reply.isPending && (isPostAuthor || (myId && myId === reply.authorId))
                      ? () => deleteCommentMutation.mutate(reply.commentId || reply.id)
                      : undefined,
                  onReport:
                    !reply.isPending && reply.authorId && myId !== reply.authorId
                      ? () => setReportComment({ commentId: reply.commentId || reply.id, authorId: reply.authorId })
                      : undefined,
                }))}
                replySlot={
                  isReplying && (
                    <form
                      onSubmit={(e) => handleSubmitReply(e, comment)}
                      className="mt-2 flex items-center gap-2 pl-1"
                    >
                      <img
                        src={myProfile?.profilePhoto || DEFAULT_AVATAR}
                        alt={t("comments.youAlt")}
                        className="w-6 h-6 rounded-full object-cover flex-shrink-0"
                      />
                      <input
                        type="text"
                        autoFocus
                        value={replyText}
                        onChange={(e) => setReplyText(e.target.value.slice(0, COMMENT_MAX_LENGTH))}
                        placeholder={t("comments.replyPlaceholder")}
                        maxLength={COMMENT_MAX_LENGTH}
                        // iOS Safari auto-zooms the page on focus for inputs under
                        // 16px computed font-size — text-xs (12px) was tripping
                        // that, so pin it directly (see ChatConversationPage).
                        style={{ fontSize: 16 }}
                        className="flex-1 px-3 py-1.5 bg-white border border-gray-200 rounded-full focus:outline-none focus:ring-2 focus:ring-primary/20"
                      />
                      <button
                        type="submit"
                        disabled={!replyText.trim() || replyCommentMutation.isPending}
                        className="p-1.5 bg-primary text-white rounded-full hover:shadow-lg transition-all disabled:opacity-50 disabled:cursor-not-allowed"
                      >
                        <Send className="w-3.5 h-3.5" />
                      </button>
                    </form>
                  )
                }
              />
            );
          })}

          {hasMoreComments && (
            <div className="flex justify-center pt-1">
              <button
                type="button"
                onClick={() => fetchNextComments()}
                disabled={isFetchingMoreComments}
                className="px-5 py-2 btn-outlined text-sm rounded-full disabled:opacity-60"
              >
                {isFetchingMoreComments
                  ? t("profileTabs.seeMoreLoading")
                  : t("profileTabs.seeMore")}
              </button>
            </div>
          )}
        </div>

        {/* Comment Input */}
        <div className="flex-shrink-0 p-4 border-t border-gray-100">
          <form onSubmit={handleSubmitComment} className="flex items-center gap-3">
            <img
              src={myProfile?.profilePhoto || DEFAULT_AVATAR}
              alt={t("comments.yourAvatarAlt")}
              className="w-8 h-8 rounded-full object-cover flex-shrink-0"
            />
            <div className="flex-1 relative">
              <input
                type="text"
                value={newComment}
                onChange={(e) => setNewComment(e.target.value.slice(0, COMMENT_MAX_LENGTH))}
                placeholder={t("comments.commentPlaceholder")}
                maxLength={COMMENT_MAX_LENGTH}
                // iOS Safari auto-zooms the page on focus for inputs under
                // 16px computed font-size — text-sm (14px) was tripping
                // that, so pin it directly (see ChatConversationPage).
                style={{ fontSize: 16 }}
                className="w-full pl-4 pr-12 py-2.5 bg-gray-100 rounded-full focus:outline-none focus:ring-2 focus:ring-primary/20 focus:bg-white transition-all"
              />
              <button
                type="submit"
                disabled={!newComment.trim() || createCommentMutation.isPending}
                className="absolute right-1.5 top-1/2 -translate-y-1/2 p-1.5 bg-primary text-white rounded-full hover:shadow-lg transition-all disabled:opacity-50 disabled:cursor-not-allowed"
              >
                <Send className="w-4 h-4" />
              </button>
            </div>
          </form>
          {newComment.length > COMMENT_MAX_LENGTH * 0.9 && (
            <p className="text-xs text-gray-400 text-right mt-1">
              {newComment.length}/{COMMENT_MAX_LENGTH}
            </p>
          )}
        </div>
    </BottomSheetModal>

    <ReportUserModal
      open={!!reportComment}
      onClose={() => setReportComment(null)}
      username={reportComment?.authorId}
      sourceType="COMMENT"
      sourceService="circle-service"
      sourceId={reportComment?.commentId}
      circleId={post?.circleId}
      onSubmit={(payload) => reportUser(payload)}
    />
    </>
  );
}
