import { reportApi, reviewApi } from "../../api/clients";
import { useMutation } from "@tanstack/react-query"
import { getErrorMessage } from "../../shared/api/getErrorMessage"


export const createSupportCase = async data => {
  try {
    const res = await reportApi.post(
      "/support/case",
      // Generated once per call (not regenerated by axios-retry, which
      // resends this exact request body) — lets the backend recognize a
      // retried submission as the same case instead of creating a duplicate
      // (and, since a retry could otherwise be miscounted as a second
      // ticket, incorrectly tripping the 2-tickets-per-24h limit).
      { ...data, clientCaseId: crypto.randomUUID() },
      { withCredentials: true }
    )
    return res.data
  } catch (error) {
    throw new Error(getErrorMessage(error))
  }
}

export const submitAppReview = async ({ rating, text, isAnonymous }) => {
  try {
    const res = await reviewApi.post(
      "/create",
      // Generated once per call (not regenerated by axios-retry, which
      // resends this exact request body) — lets the backend recognize a
      // retried submission as the same review instead of creating a
      // duplicate.
      { rating, text, isAnonymous, clientReviewId: crypto.randomUUID() },
      { withCredentials: true }
    )
    return res.data
  } catch (error) {
    throw new Error(getErrorMessage(error))
  }
}

