name: "Deploy to EC2 (Local Runner)"

on:
  push:
    branches:
      - "main"

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: "Checkout code"
        uses: actions/checkout@v3

      - name: "Install dependencies"
        run: |
          cd ~/terminal-143-frontend
          npm install

      - name: "Build project"
        run: |
          cd ~/terminal-143-frontend
          npm run build
